### ISSUE TITLE
OSX Builds Failing

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/pillow-wheels#45] opened 2016-10-04 15:14 UTC
@matthew-brett 

https://travis-ci.org/python-pillow/pillow-wheels/jobs/164959060

OSX builds were working earlier today -- and this doesn't appear to be something that's related to the Pillow code. 

Ideas?

**Comment by hugovk** [comment] 2016-10-04 16:49
Maybe caused by this?

https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/

**Comment by matthew-brett** [comment] 2016-10-04 16:59
Sounds like it's a travis-ci bug.

See this thread also : https://github.com/direnv/direnv/issues/210

Could try 

```
osx_image: xcode6.4
```

at the top of `.travis.yml` to see if that helps.   I've tried setting of a test OSX build, but it's taking an age to start.

**Comment by matthew-brett** [comment] 2016-10-04 17:06
I emailed travis-ci support, will let y'all know how it goes.

**Comment by wiredfool** [comment] 2016-10-04 17:20
That's a reasonable diagnosis:

Successful run earlier today: instance: 16782137-e409-42c8-b363-fffe4051ae83:travis-ci-osx10.9-xcode6.1-1472151920 from https://travis-ci.org/python-pillow/pillow-wheels/jobs/164947028


Failed run: instance: d9728977-df2b-4bc4-b664-ece05a87df47:travis-ci-osx10.11-xcode7.3-1475505633 from https://travis-ci.org/python-pillow/pillow-wheels/jobs/164959058

**Comment by matthew-brett** [comment] 2016-10-04 18:04
Yup - testing on the older xcode 6.4 image passes : https://travis-ci.org/matthew-brett/pillow-wheels/builds/165013350

See #46.

**Comment by wiredfool** [comment] 2016-10-04 18:13
Thanks, config changes are frustrating when they land between one run and the next.

**Comment by hugovk** [comment] 2016-10-23 09:34
Can we close this now?

**Closed** 2016-10-23 12:48 UTC
